### ISSUE TITLE
How does this relate to cgroups?

### ISSUE THREAD

**Issue by JanKanis** [pshved/timeout#10]
The documentation nor the article at coldattic.info mention Linux cgroups. I think a cgroups based solution to this problem would be way superior and it doesn't suffer from the polling disadvantages. Since this script still seems to be maintained it would at least be nice to have a mention of that in the readme or the article. See [here](http://unix.stackexchange.com/a/279175/50793) for a cgroups based script that limits memory of a process + children. CPU time could be limited in the same way.

**Comment by pshved** [comment]
Feel free to send me a documentation patch. I've been suggesting c groups privately for some time. There are some advantages to my script but c groups is a better option most of the time. 

On April 26, 2016 6:07:50 AM PDT, Jan Kanis <notifications@github.com> wrote:
>The documentation nor the article at coldattic.info mention Linux
>cgroups. I think a cgroups based solution to this problem would be way
>superior and it doesn't suffer from the polling disadvantages. Since
>this script still seems to be maintained it would at least be nice to
>have a mention of that in the readme or the article. See
>[here](http://unix.stackexchange.com/a/279175/50793) for a cgroups
>based script that limits memory of a process + children. CPU time could
>be limited in the same way.
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/pshved/timeout/issues/10

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by PhilippWendler** [comment]
I am the developer of another tool called [BenchExec](https://github.com/sosy-lab/benchexec), which allows to measure and limit resource consumption of processes using cgroups. It has a component called [runexec](https://github.com/sosy-lab/benchexec/blob/a9202161fde1274056376814c33e8b2960b0e812/doc/runexec.md), which is quite similar to the `timeout` script and more sophisticated than the [script](http://unix.stackexchange.com/a/279175/50793) that is currently linked in the readme.

Maybe you would like to add a link to BenchExec to the readme?

**Comment by pshved** [comment]
Hey Philipp!  Did you develop it for CPAchecker, like I developed timeout for BLAST? ;-)  Feel free to send me a pull request putting a link to your tool next to a recommendation on cgroups.  Will be happy to merge.
