### ISSUE TITLE
Can't invoke from Makefile

### ISSUE THREAD

**Issue by regellosigkeitstaxiom** [pshved/timeout#8]
From command line:
```
$ timeout -m 100 ./a.out 
MEM CPU 0.11 MEM 82860 MAXMEM 82860 STALE 0
<time name="ALL">140</time>
```

`Makefile` contents:
```Makefile
all:
    timeout -m 100 ./a.out
```
Run `make`:
```
$ make
timeout -m 100 ./a.out
timeout: invalid option -- 'm'
Try 'timeout --help' for more information.
Makefile:2: recipe for target 'all' failed
make: *** [all] Error 125
```

**Comment by pshved** [comment]
You're trying to income the default version of timeout that comes with the  shell. Try specifying the full path to the script,  E. G. /home/me/bin/timeout -m... 

On December 26, 2015 12:18:51 AM MST, regellosigkeitstaxiom <notifications@github.com> wrote:
>From command line:
>```
>$ timeout -m 100 /aout 
>*some output*
>MEM CPU 011 MEM 82860 MAXMEM 82860 STALE 0
><time name="ALL">140</time>
>```
>
>`Makefile` contents:
>```Makefile
>all:
>    cc testc
>    timeout -m 100 /aout
>```
>Run `make`:
>```
>$ make
>cc testc
>timeout -m 100 /aout
>timeout: invalid option -- 'm'
>Try 'timeout --help' for more information
>Makefile:2: recipe for target 'all' failed
>make: *** [all] Error 125
>```
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/pshved/timeout/issues/8

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
